### PR TITLE
Friendship associations  v1

### PR DESCRIPTION
**Pull request by Amalcxc**
- Create a model with associations
- made the controllers for it
- view to display the buttons to accept and delete
-  made routes for all

### CODE REVIEW

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑🛑🛑🛑🛑🛑**

Hello @Amalcxc 
Great work on this project. Your repo looks professional. That reflects on the amount of work you've put in👏👏

However, let's make few changes to make sure that the project gets approved👌👌
Add the following features as specified in the milestone requirements.

[REQUIRED]: User can see friendships requests
[REQUIRED]: User has to accept friendship request to start friendship
[REQUIRED]: User can reject a friendship request
[REQUIRED]: Posts timeline includes posts written by logged-in user and their friends
[REQUIRED]: There is no button to invite user to friendship on single user page, kindly add it
[REQUIRED]: Kindly add unit and integration tests.

That's it👍👍

Make the requested changes and ask for another review.

Happy coding💻💻

**Comment by Amalcxc** [comment]
the comments that the last code reviewer made didn't help. as the app already has most of these functionalities 

here are some screenshots.

1. User can see friendship requests?
     - go to the link that says "See Profile" of the user you are sign-in as 
Screen Shot 2021-06-10 at 6 11 26 PM

2. User has to accept friendship request to start a friendship and User can reject a friendship request
      - as you can see in the Above photo a user can accept and reject requests

3.  Posts timeline includes posts written by logged-in user and their friends
      - go to timeline in navbar
 Screen Shot 2021-06-10 at 6 23 21 PM

4. There is no button to invite a user to friendship on single-user page
     - the "invite link" is how you invite people.
Screen Shot 2021-06-10 at 6 27 35 PM

**Review by george-shammar — CHANGES_REQUESTED** [review]
### **STATUS:CHANGES REQUESTED** :recycle: :recycle: :construction: :construction_worker:

Good effort so far @Amalcxc  

You have implemented some of the requirements of this milestone.

Please see my review below: :point_down: :point_down: 

Consistent with the review comments of the last reviewer, the following changes are still required: I have included screenshots this time, following your objection to the last TSE's review.

- [ ] User should be able to see friendship requests. Please see screenshot below. Note that I have already sent a friendship request to this user from another user.
image

- [ ] User has to accept friendship request to start friendship. If a user cannot see friendship request, it implies that same user cannot accept or reject the request.

- [ ] User should be able to reject a friendship request. Same as above.

- [ ] Posts timeline includes posts written by logged-in user and their friends. If friendship status is not confirmed, timeline post cannot be updated.

- [ ] There is no button to invite user to friendship on single user page, kindly add it. Please see screenshot below. This is another user's show page, I'm logged in as a different user and there's no where on this user's show page to invite him to friendship.
image

- [ ] You have implemented some tests but integration test is also required.

Please don't be frustrated or irritated by the required changes. Do your best as you've always done.

I'll be happy to share my screen with you to show you how your application behaves on this side.

Please make the required changes and submit another CRR when you're ready.

Feel free to drop your message here if you require clarification or support.

Cheers and happy coding. :smile:

**Comment by rukundoeric** [comment]
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - Follows gitwork-flow.  💯
  - Codebase looks clean and professinal. 💯 
  - Feedback implemented. 💯 

- ### To Improve
  - N/A

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

**Pull request merged**
